//How to Play Rock, Paper, Scissors.
//https://www.wikihow.com/Play-Rock,-Paper,-Scissors


// PROBLEM SOLVING
// 1. Understand the Problem
//To gain clarity and understanding of the problem, write it down,
//reword it in plain English until it makes sense to you.

// Write a program that takes specific
// user's input (Rock, Paper, Scissors)
// and then compares the input value with a 
// randomly value generated by the computer,
// evaluates which value is 'stronger' and returns result
// as win (1 point) , the program runs the same function 
// for namerous rounds , the one who reached 5 wins first , wins.

// 2. Plan
//Q-Does your program have a user interface? 

//A-Display a prompt box 

//Q-What functionality will the interface have?

//A-prompt box asks the user to choose a weapon (rock,paper,scissors),
//and output a message which contains the user's chosen weapon,
//the computer's weapon and based on that who won the round.

//Q-What inputs will your program have? 

//A-User's chosen weapon , for each round.

//Q-Will the user enter data or will you get input from somewhere else?

//A-yes the user will the data in the prompt box.
//and the computer will generate a random value.

//Q-What’s the desired output?

//A-two desired outputs 
// 1st - who won the current round (user vs computer)
// 2nd - who won the game (reached 5 wins first)


//Q-Given your inputs, what are the steps necessary to return the desired output?

//A- compare between user's input value and the computer's randomly generated value,
//detrmine which value is greater and decide who won the round.
// count user/computer wins , first to reach 5 wins , end the game and return a message.

//Pseudo Code

//when the user enters a string input of chosen weapon (out of 3) via prompt
//assign an int to a string value.
//Initialize a user/computer win-counter-variable and set its value to zero
//While user/computer win-counter-variable is smaller than 5
//compare the user's input value with a randomly generated int by the computer.
//add one to either user/computer win-counter-variable.
//else end the game and return a message with the announcment of the winner.

// 3. Divide and Conquer

 





//return computer's weapon result

function computerPlay () {

    //return a round random number between min to max (included)

    function getRndInteger (min, max) {
    return Math.floor(Math.random() * (max - min + 1) ) + min;
    
}

//return a round random number between 1 to 3 (included)

let randomValue = getRndInteger(1,3);


    if (randomValue === 1) {
        return 'rock';
    }
    else if (randomValue === 2) {
        return 'paper'
    }
    else {
        return 'scissors'
    }
    
}



// computer's weapon is randomly chosen.
const computerSelection = computerPlay();


//user enters his chosen weapon via prompt 

function userPlay () {
    return prompt("Choose your weapon Rock,Paper or Scissors", "").toLowerCase();
} 

const playerSelection = userPlay();

 //one round in a game , compares user's weapon selection vs computer's weapon
// then returns the appropiate result for the different cases.
function playRound(playerSelection, computerSelection) {
    if (playerSelection === 'rock' && computerSelection === 'rock') {
        return 'It\'s a tie!'; 
    } else if (playerSelection === 'rock' && computerSelection === 'paper') {
        return 'You Lose! Paper beats Rock';
    } else if (playerSelection === 'rock' && computerSelection === 'scissors') {
        return 'You Win! Rock beats Scissors';
    } else if (playerSelection === 'paper' && computerSelection === 'rock') {
        return 'You Win! Paper beats Rock';
    } else if (playerSelection === 'paper' && computerSelection === 'paper') {
        return 'It\'s a tie!';
    } else if (playerSelection === 'paper' && computerSelection === 'scissors') {
        return 'You Lose! Scissors beats Paper';
    } else if (playerSelection === 'scissors' && computerSelection === 'rock') {
        return 'You Lose! Rock beats Scissors';
    } else if (playerSelection === 'scissors' && computerSelection === 'paper') {
        return 'You Win! Scissors beats Paper';
    } else if (playerSelection === 'scissors' && computerSelection === 'scissors') {
        return 'It\'s a tie!';
    } else if (playerSelection === null) {
        return; 
    } else {
        return 'Choose a valid weapon - either Rock,Paper or Scissors';
    }
  }
  

  //console.log(playRound(playerSelection, computerSelection));
  //console.log('computer\'s weapon:', computerSelection);



  function evaluation () {
    let userScore = 0; 
    let computerScore = 0;
    let roundResult = playRound(playerSelection, computerSelection);


    if (userScore < 5 && computerScore < 5 && roundResult === 'You Win! Rock beats Scissors' ||roundResult === 'You Win! Paper beats Rock' || roundResult === 'You Win! Scissors beats Paper' )  {
       //add one win to user's score.
       
       return 'user\'s wins:' //,userScore;
       //userScore += 1 
        
} else if (userScore < 5 && computerScore < 5 && roundResult === 'You Lose! Paper beats Rock' || roundResult === 'You Lose! Scissors beats Paper' || roundResult === 'You Lose! Rock beats Scissors') { 
    //add one win to computer's score.
    
    return 'computer\'s wins:' //computerScore += 1 ,  //, computerScore;
       
} else {
    return 'tie...'
}
}

//console.log(evaluation());

//play a 5 round game that keeps score and reports a winner or loser at the end.






